keys:
  - &users:
    - &joseph-admin age1sea7mljrfuu0xakccvvn9ep0emaq76czwqp93x4v6hds4d3jpcastc0teh
  - &hosts:
    - &joseph-system age1qa43nn7cd70ydew8csgxawc9rsn2z0nqfh0lwp2e6qzu2cyr8fsq2a6289
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *joseph-admin
      - *joseph-system
