#!/usr/bin/env bash
LANG="en_US.utf8"

if [[ "$@" ]]
then

    selection=$*

    if [[ "$selection" == "No YubiKey Inserted!" ]]; then
        exit
    fi

    name=${selection% -*}
    code=${selection#*- }
    setsid bash -c "echo -n '$code' | xclip -selection clipboard" &>/dev/null &
    notify-send -t 10000 -u low "Copied the TOTP for $name to the clipboard." "The code is: $code"
    exit

else

    echo -en "\x00prompt\x1fSelect TOTP Code\n"

    if ! codes=$(ykman oath accounts code)
    then
        notify-send -t 5000 "No YubiKey Inserted!" "Please plug in your security key to access TOTP codes."
        echo "No YubiKey Inserted!"
        exit
    fi

    for x in "$codes"
    do
        name=${x%%:*}
        code=${x##* }
        printf "%s - %s\n" $name $code
    done

fi
