#!/usr/bin/env bash
LANG="en_US.utf8"

if [[ "$@" ]]
then

    selection=$*
    label=$(echo "${selection%:*}" | xargs)
    devname=${selection##* }
    target=/media/${devname##*/}

    if mountpoint $target -q; then

        sudo umount $target

        dunstify -t 5000 -u low "Unmounted device \"$label\" from $target."
    else

        mkdir -p $target
        uid=$(id -u $(whoami))
        gid=$(id -g $(whoami))
        sudo mount -o uid=${uid},gid=${gid},noexec $devname $target 

        dunstify -t 5000 -u low "Mounted device \"$label\" to $target."

    fi

    # selection=$*
    #
    # if [[ "$selection" == "No YubiKey Inserted!" ]]; then
    #     exit
    # fi
    #
    # name=${selection% -*}
    # code=${selection#*- }
    # setsid bash -c "printf '%s' '$code' | xclip -selection clipboard" >/dev/null 2>&1 &
    # dunstify -t 10000 -u low "Copied the code for $name to the clipboard." "The code is: $code"
    exit

else

    echo -en "\x00prompt\x1fMount or Unmount\n"

    devices=$(lsblk -riApn -o NAME,TYPE,LABEL,SIZE,FSTYPE,MOUNTPOINT | rg -v '^/dev/nvme' --color=never | rg 'part' --color=never)

    for x in $(echo "$devices" | tr ' ' ';')
    do
        IFS=';' read -r -a fields <<< "$x"
        if [[ "${#fields[@]}" == "5" ]]; then
            printf "%-20b: %6s %-6s %-40s %s\n" "${fields[@]:2:3}" "" "${fields[0]}"
        else
            printf "%-20b: %6s %-6s %-40s %s\n" "${fields[@]:2:4}" "${fields[0]}"
        fi
    done

fi
