#!/usr/bin/env bash

LANG="en_US.utf8"

if [ "$@" ]
then

    selection=$* 

    if [[ "$selection" == "No YubiKey Inserted!" ]]; then
      exit
    fi

    name=${selection% -*}
    code=${selection#*- }
    setsid bash -c "printf '%s' '$code' | xclip -selection clipboard" >/dev/null 2>&1 &
    dunstify -t 10000 -u low "Copied the code for $name to the clipboard." "The code is: $code"
    exit

else

    echo -en "\x00prompt\x1fSelect OATH Code\n"

    codes=$(ykman oath accounts code || echo "ERROR")

    if [[ "$codes" == "ERROR" ]]; then
      dunstify -t 5000 -u high "No YubiKey Inserted!" "Please plug in your security key to access OATH codes."
      echo "No YubiKey Inserted!"
      exit
    fi

    for x in $(echo "$codes" | rg '^(.+?):.*\s(\d{6})$' -r '$1:$2' -o --color=never)
    do
        name=${x%:*}
        code=${x#*:}
        printf "%s - %s\n" $name $code
    done

fi
